// <auto-generated />
using System;
using ChessLegacy.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChessLegacy.API.Migrations
{
    [DbContext(typeof(ChessLegacyContext))]
    [Migration("20260327114030_AddAmistad")]
    partial class AddAmistad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("ChessLegacy.API.Models.ActividadDiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Fecha")
                        .IsUnique();

                    b.ToTable("ActividadesDiarias");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Amistad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmigoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AmigoId");

                    b.HasIndex("UsuarioId", "AmigoId")
                        .IsUnique();

                    b.ToTable("Amistades");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Apertura", b =>
                {
                    b.Property<string>("ECO")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("MovimientosIniciales")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Variante")
                        .HasColumnType("TEXT");

                    b.HasKey("ECO");

                    b.HasIndex("Nombre");

                    b.ToTable("Aperturas");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Intento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvaluacionCentipawns")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaIntento")
                        .HasColumnType("TEXT");

                    b.Property<string>("MejorMovimiento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovimientoJugado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PosicionId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ScoreEstilo")
                        .HasColumnType("REAL");

                    b.Property<double>("ScoreFinal")
                        .HasColumnType("REAL");

                    b.Property<double>("ScorePrecision")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PosicionId");

                    b.ToTable("Intentos");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnioNacimiento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biografia")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PerfilEstilo")
                        .HasColumnType("TEXT");

                    b.Property<double>("PesoAtaqueRey")
                        .HasColumnType("REAL");

                    b.Property<double>("PesoControlCentro")
                        .HasColumnType("REAL");

                    b.Property<double>("PesoFinales")
                        .HasColumnType("REAL");

                    b.Property<double>("PesoSacrificio")
                        .HasColumnType("REAL");

                    b.Property<double>("PesoSimplificacion")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.LogroUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaObtenido")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Codigo")
                        .IsUnique();

                    b.ToTable("Logros");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaracteristicasEstilo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EvaluacionStockfish")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FaseJuego")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FenAntes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FenDespues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroMovimiento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartidaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("San")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoMovimiento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FaseJuego");

                    b.HasIndex("PartidaId", "NumeroMovimiento");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AperturaNombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoECO")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorJugador")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EloJugador")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EloOponente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("JugadorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Oponente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PGN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resultado")
                        .HasColumnType("TEXT");

                    b.Property<string>("VarianteNombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Anio");

                    b.HasIndex("CodigoECO");

                    b.HasIndex("JugadorId", "CodigoECO");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.PartidaJugada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorJugador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsTorneo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaJugada")
                        .HasColumnType("TEXT");

                    b.Property<string>("Maestro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pgn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalMovimientos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "FechaJugada");

                    b.ToTable("PartidasJugadas");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Posicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FEN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovimientoHistorico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PartidaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoPosicion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.ToTable("Posiciones");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.ProgresoApertura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aciertos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apertura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Intentos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sesiones")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SesionesPerfectas")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UltimaSesion")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Variante")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Apertura", "Variante", "Color")
                        .IsUnique();

                    b.ToTable("Progresos");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Foto")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximaRacha")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RachaActual")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UltimaActividad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.ActividadDiaria", b =>
                {
                    b.HasOne("ChessLegacy.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Amistad", b =>
                {
                    b.HasOne("ChessLegacy.API.Models.Usuario", "Amigo")
                        .WithMany()
                        .HasForeignKey("AmigoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChessLegacy.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Amigo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Intento", b =>
                {
                    b.HasOne("ChessLegacy.API.Models.Posicion", "Posicion")
                        .WithMany("Intentos")
                        .HasForeignKey("PosicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posicion");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.LogroUsuario", b =>
                {
                    b.HasOne("ChessLegacy.API.Models.Usuario", "Usuario")
                        .WithMany("Logros")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Movimiento", b =>
                {
                    b.HasOne("ChessLegacy.API.Models.Partida", "Partida")
                        .WithMany("Movimientos")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Partida", b =>
                {
                    b.HasOne("ChessLegacy.API.Models.Apertura", "Apertura")
                        .WithMany("Partidas")
                        .HasForeignKey("CodigoECO");

                    b.HasOne("ChessLegacy.API.Models.Jugador", "Jugador")
                        .WithMany("Partidas")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apertura");

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.PartidaJugada", b =>
                {
                    b.HasOne("ChessLegacy.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Posicion", b =>
                {
                    b.HasOne("ChessLegacy.API.Models.Partida", "Partida")
                        .WithMany("Posiciones")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.ProgresoApertura", b =>
                {
                    b.HasOne("ChessLegacy.API.Models.Usuario", "Usuario")
                        .WithMany("Progresos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Apertura", b =>
                {
                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Jugador", b =>
                {
                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Partida", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Posiciones");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Posicion", b =>
                {
                    b.Navigation("Intentos");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Usuario", b =>
                {
                    b.Navigation("Logros");

                    b.Navigation("Progresos");
                });
#pragma warning restore 612, 618
        }
    }
}
