// <auto-generated />
using System;
using ChessLegacy.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChessLegacy.API.Migrations
{
    [DbContext(typeof(ChessLegacyContext))]
    partial class ChessLegacyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("ChessLegacy.API.Models.Apertura", b =>
                {
                    b.Property<string>("ECO")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("MovimientosIniciales")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Variante")
                        .HasColumnType("TEXT");

                    b.HasKey("ECO");

                    b.HasIndex("Nombre");

                    b.ToTable("Aperturas");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Intento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvaluacionCentipawns")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaIntento")
                        .HasColumnType("TEXT");

                    b.Property<string>("MejorMovimiento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovimientoJugado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PosicionId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ScoreEstilo")
                        .HasColumnType("REAL");

                    b.Property<double>("ScoreFinal")
                        .HasColumnType("REAL");

                    b.Property<double>("ScorePrecision")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PosicionId");

                    b.ToTable("Intentos");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnioNacimiento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biografia")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PerfilEstilo")
                        .HasColumnType("TEXT");

                    b.Property<double>("PesoAtaqueRey")
                        .HasColumnType("REAL");

                    b.Property<double>("PesoControlCentro")
                        .HasColumnType("REAL");

                    b.Property<double>("PesoFinales")
                        .HasColumnType("REAL");

                    b.Property<double>("PesoSacrificio")
                        .HasColumnType("REAL");

                    b.Property<double>("PesoSimplificacion")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaracteristicasEstilo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EvaluacionStockfish")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FaseJuego")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FenAntes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FenDespues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroMovimiento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartidaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("San")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoMovimiento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FaseJuego");

                    b.HasIndex("PartidaId", "NumeroMovimiento");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AperturaNombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoECO")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorJugador")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EloJugador")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EloOponente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("JugadorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Oponente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PGN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resultado")
                        .HasColumnType("TEXT");

                    b.Property<string>("VarianteNombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Anio");

                    b.HasIndex("CodigoECO");

                    b.HasIndex("JugadorId", "CodigoECO");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Posicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FEN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovimientoHistorico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PartidaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoPosicion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.ToTable("Posiciones");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Intento", b =>
                {
                    b.HasOne("ChessLegacy.API.Models.Posicion", "Posicion")
                        .WithMany("Intentos")
                        .HasForeignKey("PosicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posicion");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Movimiento", b =>
                {
                    b.HasOne("ChessLegacy.API.Models.Partida", "Partida")
                        .WithMany("Movimientos")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Partida", b =>
                {
                    b.HasOne("ChessLegacy.API.Models.Apertura", "Apertura")
                        .WithMany("Partidas")
                        .HasForeignKey("CodigoECO");

                    b.HasOne("ChessLegacy.API.Models.Jugador", "Jugador")
                        .WithMany("Partidas")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apertura");

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Posicion", b =>
                {
                    b.HasOne("ChessLegacy.API.Models.Partida", "Partida")
                        .WithMany("Posiciones")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Apertura", b =>
                {
                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Jugador", b =>
                {
                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Partida", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Posiciones");
                });

            modelBuilder.Entity("ChessLegacy.API.Models.Posicion", b =>
                {
                    b.Navigation("Intentos");
                });
#pragma warning restore 612, 618
        }
    }
}
